### ISSUE TITLE
Multi-label training

### ISSUE THREAD

**Issue by Sara-Ahmed** [Alibaba-MIIL/ML_Decoder#11]
Thanks a lot for sharing your work. 
I have a question regarding this line
target = target.max(dim=1)[0]
Why are you taking the maximum of the target and the predictions? are you considering the problem as single class classification instead of multi-label?

Thanks a lot,

**Comment by mrT23** [comment]
Its just an artifact of the API of COCO dataset.
see https://github.com/Alibaba-MIIL/ML_Decoder/issues/7

In practice, we solve COCO dataset just like any other multi-label dataset.

To prevent future confusion, i refactored this line to be an inner line of CocoDetection function
https://github.com/Alibaba-MIIL/ML_Decoder/blob/main/src_files/helper_functions/helper_functions.py#L124
