### ISSUE TITLE
can you share the backbone pretrain weight  on open image ?

### ISSUE THREAD

**Issue by ckvic3** [Alibaba-MIIL/ML_Decoder#17]
Thank you for your work!  It's a very interesting work. I'm reproducing your's work and trying to do some research based on your work. But the Tresnet-L is too big to train, so I want to start with Tresnet-m. But I am not able to find the pre-trained weights of Tresnet-m on open image dataset. So I'm asking here if you can share the pre-trained weights of the Tresnet series of models on open-image?

**Comment by mrT23** [comment]
sorry, i cant at this moment.

**Comment by ckvic3** [comment]
ok, thank you for your reply!
