### ISSUE TITLE
Can not reproduce the tresnet-l mAP on coco

### ISSUE THREAD

**Issue by FunnyClown** [Alibaba-MIIL/ML_Decoder#19]
Hi, first thanks for you to share your great work!
Here, I rerun all models in the model_zoo and got the same mAP except the tresnet-l on COCO(85.57 in my workspace), maybe a wrong model is uploaded on git?
I notice the name of tresnet-l is a little bit different from other models.

**Comment by mrT23** [comment]
what script did you run ? what resolution ? have you loaded the pretrain correctly ?

**Comment by FunnyClown** [comment]
Hi, the resolution is 448 when I use the tresnet-l(layer_list is 3,4,23,3, first_two_layers=Bottleneck) with MLDecoder.
The inplace_abn is installed by `pip install inplace_abn`.
I use the same code exactly when running the tresnet-m, l, xl, and I reproduce the same result for M and XL but not for L.

**Comment by mrT23** [comment]
i suspect you have an issue with loading the pretrained model.

what do you mean you reproduced with 'tresnet-m' and 'tresnet-xl' ? i currently do not provide here their open-images pre-trained weights.

triple-check you are properly loading the correct weights for tresnet-l
( https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ML_Decoder/tresnet_l_pretrain_ml_decoder.pth )

try setting
`model.load_state_dict(filtered_dict, strict=False)` ->
`model.load_state_dict(filtered_dict, strict=True)`

also try running inference with tresnet-l on the MS-COCO trained model, and make sue you reproduce results (90.0)
