### ISSUE TITLE
Using NUS-WIDE Dataset for zeroshot classification Task

### ISSUE THREAD

**Issue by aliman80** [Alibaba-MIIL/ML_Decoder#28]
Hi, Thank you for your excellent work, I want to apply this model for a zero-shot learning task on the nus-wide dataset. In the repository, we do have csv.dat file which contains list of images but we don't have the dataset on which I can run inference or validation or training. 
Will it be possible for you to share your relevant dataset so that i can proceed please? 

regards

**Comment by mrT23** [comment]
Hi aliman

I appreciate the interest, and the issues opened. you were right about a previous bug (bad commit).
However, you need to adjust your expectations. We won't be able to share a full end-to-end tutorial on ZSL. some things you will have to do on your own. We provide a dedicated implementation for the methods proposed in our paper, in different fields. 
What we already shared is far more than what is common in other multi-label\ZSL papers.

Anyway, we already shared a link to nus-wide dataset in our ASL paper
https://drive.google.com/file/d/0B7IzDz-4yH_HMFdiSE44R1lselE/view
![image](https://user-images.githubusercontent.com/21198860/159277813-7b236720-5a0c-40be-9b95-668e6da0bfd9.png)

**Comment by aliman80** [comment]
I am really sorry that I disturb you as I am a novice in the field so I couldn't realize the level of support which I asked for.

Thank you very much again for all the previous support and for this latest dataset. 

Regards
