### ISSUE TITLE
Doubt in the performance on ResNet backbone

### ISSUE THREAD

**Issue by yzqinjacob** [Alibaba-MIIL/ML_Decoder#29]
Hi! Thanks a lot for sharing this valuable work.
But I have some questions for the performance of ML_decoder in ResNet backbone. It seems that you haven't released the RessNet version in your code but some relevant datas appear in your paper. I just exchange the TResNet into ResNet but the mAP score is only 81.1, so far from your released score 87.1.
So I wanna ask you whether the experimental settings on ResNet and TResNet are different or I mistakenly combine ResNet with ML_decoder, it will be very nice of you to realese the function of ResNet version. 
Thanks again!

**Comment by mrT23** [comment]
Hello

we have tested ResNet with ML-Decoder in the paper on single-label classification (figure 6), it works very well.
results of ResNet on MS-COCO we have in [ASL paper](https://arxiv.org/abs/2009.14119).

I am not sure what configuration you ran, or even which ResNet (18, 50, 101 ??).
anyway - why the big score gap:
1) TResNet are dramatically better models than plain ResNet
2) We are you using good pretrain for TResNet (imageNet 21K or OpenImages), while you are probably using a bad 1K pretrain.

hence, i wont release ResNet models. move to newer and better models, like TResNet.
