### ISSUE TITLE
Training Pefromance of ZSL code ,final mAP with tresnet-m is 15.6

### ISSUE THREAD

**Issue by aliman80** [Alibaba-MIIL/ML_Decoder#30]
Hi, I have tried to train the tresnet-m model on nus-wide dataset but i got mAP of 15.6 after 40 epochs. May i ask you suggestion what am i doing wrong here , i didn't change any code.
If you can answer this will help a lot
Regards

**Comment by giladsharir** [comment]
Hi @aliman80 , 
can you please share the training logs/outputs ?
Which model_path did you use for tresnet-m ?

**Comment by aliman80** [comment]
Thank you very much for your response, I tried to use tresnet-m but it was giving me error that my saved model and current model dimensions mismatch so i trained it from scratch. Can you guide what should i don next.

**Comment by aliman80** [comment]
RuntimeError: Error(s) in loading state_dict for TResNet:
        size mismatch for head.decoder.duplicate_pooling: copying a param with shape torch.Size([80, 768, 1]) from checkpoint, the shape in current model is torch.Size([768, 1]).
        size mismatch for head.decoder.duplicate_pooling_bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([1]).
This is the error which i obtain , Pleae guide where i am messing up

**Comment by giladsharir** [comment]
thanks for reporting this issue. 
We fixed it, and now you can train tresnet-m with : 
`--model_path=https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/models/tresnet_m_miil_21k.pth`

**Comment by aliman80** [comment]
Thank you so very much, for your response and support 
Thanks again

**Comment by aliman80** [comment]
Hi,  Thanks for your continuous support, I have been able to run the ZSL file but I am receiving these results;

mAP score regular 1.14, mAP score EMA 1.14
current_mAP = 1.14, highest_mAP = 1.14

**Comment by aliman80** [comment]
Thank you , i used wrong lr that's why it caused me error.

Thanks again for your support
