### ISSUE TITLE
Query Augmentations: Issue :from randaugment import RandAugment

### ISSUE THREAD

**Issue by aliman80** [Alibaba-MIIL/ML_Decoder#38]
Hi thanks for your continuous support, I have now reproduced results till 29.9 but I don't know where are we adding query augmentations,  I tried to use randaugment to import RandAugment but it's giving me an error. Any hint as i has spent lot of time googling it to fix this error.

Thanks again for all your time and response

**Comment by giladsharir** [comment]
Please follow the details in the paper for implementing the query augmentations.  We currently don't have this feature in this repo.

**Comment by aliman80** [comment]
ok,Thank you so much for your support and guidance, i really cant thank you much for your response and guidance.

Thanks again
