### ISSUE TITLE
Reproducing mAP with mscoco2014 dataset

### ISSUE THREAD

**Issue by ghkhk** [Alibaba-MIIL/ML_Decoder#39]
Hi, thanks for your work.
I tried to reproduce the mAP result using the mscoco dataset. 
I changed only the mscoco 2014 dataset path. 
but i get the higher mAP result at only 7 epoch.

Could you help me to reproduce your results from the article, 90.1% ?

my pytorch version is 1.9.0,  py3.8_cuda11.1_cudnn8.0.5_0.

----------------------------------------------------------------------
python train.py --data '{mypath}/dataset/mscoco2014' --model_name tresnet_l

creating model tresnet_l...
done
loading annotations into memory...
Done (t=5.00s)
creating index...
index created!
loading annotations into memory...
Done (t=4.84s)
creating index...
index created!
len(val_dataset)):  40137
len(train_dataset)):  40137
python3.8/site-packages/torch/optim/lr_scheduler.py:129: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "

Epoch [0/40], Step [000/717], LR 4.0e-06, Loss: 1011.0
Epoch [0/40], Step [100/717], LR 4.1e-06, Loss: 190.3
Epoch [0/40], Step [200/717], LR 4.3e-06, Loss: 194.4
Epoch [0/40], Step [300/717], LR 4.7e-06, Loss: 181.4
Epoch [0/40], Step [400/717], LR 5.2e-06, Loss: 148.3
Epoch [0/40], Step [500/717], LR 5.8e-06, Loss: 104.6
Epoch [0/40], Step [600/717], LR 6.6e-06, Loss: 119.5
Epoch [0/40], Step [700/717], LR 7.5e-06, Loss: 102.9
starting validation
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
mAP score regular 73.91, mAP score EMA 9.81
current_mAP = 73.91, highest_mAP = 73.91

[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Epoch [1/40], Step [000/717], LR 7.7e-06, Loss: 100.9
Epoch [1/40], Step [100/717], LR 8.7e-06, Loss: 104.8
Epoch [1/40], Step [200/717], LR 9.9e-06, Loss: 81.7
Epoch [1/40], Step [300/717], LR 1.1e-05, Loss: 80.9
Epoch [1/40], Step [400/717], LR 1.3e-05, Loss: 95.3
Epoch [1/40], Step [500/717], LR 1.4e-05, Loss: 75.9
Epoch [1/40], Step [600/717], LR 1.6e-05, Loss: 85.0
Epoch [1/40], Step [700/717], LR 1.8e-05, Loss: 72.1
starting validation
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
mAP score regular 84.85, mAP score EMA 37.31
current_mAP = 84.85, highest_mAP = 84.85

[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Epoch [2/40], Step [000/717], LR 1.8e-05, Loss: 72.3
Epoch [2/40], Step [100/717], LR 2.0e-05, Loss: 66.6
Epoch [2/40], Step [200/717], LR 2.2e-05, Loss: 81.3
Epoch [2/40], Step [300/717], LR 2.4e-05, Loss: 74.3
Epoch [2/40], Step [400/717], LR 2.6e-05, Loss: 74.9
Epoch [2/40], Step [500/717], LR 2.9e-05, Loss: 61.5
Epoch [2/40], Step [600/717], LR 3.1e-05, Loss: 61.7
Epoch [2/40], Step [700/717], LR 3.3e-05, Loss: 63.9
starting validation
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)

mAP score regular 87.93, mAP score EMA 64.79
current_mAP = 87.93, highest_mAP = 87.93

[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Epoch [3/40], Step [000/717], LR 3.4e-05, Loss: 68.5
Epoch [3/40], Step [100/717], LR 3.6e-05, Loss: 80.3
Epoch [3/40], Step [200/717], LR 3.9e-05, Loss: 66.3
Epoch [3/40], Step [300/717], LR 4.1e-05, Loss: 61.4
Epoch [3/40], Step [400/717], LR 4.4e-05, Loss: 71.4
Epoch [3/40], Step [500/717], LR 4.6e-05, Loss: 69.3
Epoch [3/40], Step [600/717], LR 4.9e-05, Loss: 73.8
Epoch [3/40], Step [700/717], LR 5.2e-05, Loss: 72.1
starting validation
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
mAP score regular 89.95, mAP score EMA 76.45
current_mAP = 89.95, highest_mAP = 89.95

[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Epoch [4/40], Step [000/717], LR 5.2e-05, Loss: 66.4
Epoch [4/40], Step [100/717], LR 5.5e-05, Loss: 51.1
Epoch [4/40], Step [200/717], LR 5.7e-05, Loss: 54.9
Epoch [4/40], Step [300/717], LR 6.0e-05, Loss: 62.6
Epoch [4/40], Step [400/717], LR 6.2e-05, Loss: 68.7
Epoch [4/40], Step [500/717], LR 6.5e-05, Loss: 72.2
Epoch [4/40], Step [600/717], LR 6.8e-05, Loss: 73.3
Epoch [4/40], Step [700/717], LR 7.0e-05, Loss: 82.4
starting validation
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
mAP score regular 91.72, mAP score EMA 82.19
current_mAP = 91.72, highest_mAP = 91.72

[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Epoch [5/40], Step [000/717], LR 7.0e-05, Loss: 46.3
Epoch [5/40], Step [100/717], LR 7.3e-05, Loss: 60.6
Epoch [5/40], Step [200/717], LR 7.5e-05, Loss: 72.7
Epoch [5/40], Step [300/717], LR 7.7e-05, Loss: 49.8
Epoch [5/40], Step [400/717], LR 8.0e-05, Loss: 52.6
Epoch [5/40], Step [500/717], LR 8.2e-05, Loss: 65.1
Epoch [5/40], Step [600/717], LR 8.4e-05, Loss: 68.5
Epoch [5/40], Step [700/717], LR 8.6e-05, Loss: 64.4
starting validation
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
mAP score regular 93.18, mAP score EMA 85.92
current_mAP = 93.18, highest_mAP = 93.18

[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Epoch [6/40], Step [000/717], LR 8.6e-05, Loss: 53.7
Epoch [6/40], Step [100/717], LR 8.8e-05, Loss: 59.1
Epoch [6/40], Step [200/717], LR 8.9e-05, Loss: 69.9
Epoch [6/40], Step [300/717], LR 9.1e-05, Loss: 55.9
Epoch [6/40], Step [400/717], LR 9.3e-05, Loss: 53.5
Epoch [6/40], Step [500/717], LR 9.4e-05, Loss: 56.8
Epoch [6/40], Step [600/717], LR 9.5e-05, Loss: 67.0
Epoch [6/40], Step [700/717], LR 9.6e-05, Loss: 53.2
starting validation
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
[W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
mAP score regular 94.25, mAP score EMA 88.75
current_mAP = 94.25, highest_mAP = 94.25

----------------------------------------------------------------------

* [W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool) warning doesn't matter. so i think the warning message can be ignored -https://github.com/pytorch/pytorch/issues/57273

**Comment by limengyang1992** [comment]
I have the same problem, how did you solve it?

**Comment by Q1ngS0ng** [comment]
> I have the same problem, how did you solve it?

what's the kind of GPUs do you use? I cannot run code successfully on RTX3090T_T
