### ISSUE TITLE
Question about wordvec_array.pth

### ISSUE THREAD

**Issue by volgachen** [Alibaba-MIIL/ML_Decoder#4]
Hello, I am interested in your work, especially for its generalizability to new unseen classes. It seems that _wordvec_array.pth_ provides linguistic priors for unseen classes. Could you please elaborated on how to generate this file? Thanks.

**Comment by mrT23** [comment]
The file contains a _word2vec_ transformation of the 925 seen + 81 unseen classes labels in nus-wide  dataset.

it is very common to use this kind of transformation for multi-label zero-shot predictions.

the word2vec transformation is based on the fasttext engine:
https://fasttext.cc/docs/en/crawl-vectors.html

**Comment by volgachen** [comment]
> The file contains a _word2vec_ transformation of the 925 seen + 81 unseen classes labels in nus-wide dataset.
> 
> it is very common to use this kind of transformation for multi-label zero-shot predictions.
> 
> the word2vec transformation is based on the fasttext engine: https://fasttext.cc/docs/en/crawl-vectors.html

Thank for your explanation.
