### ISSUE TITLE
Difference between GZSL and ZSL mAPs 

### ISSUE THREAD

**Issue by aliman80** [Alibaba-MIIL/ML_Decoder#40]
Hi, thank you for your support, I am getting the mAP values after running the train.ZSL file s but how to obtain GZSL values. Also if you can guide how to get F1 scores for different K values as mentioned in paper; Can you share the computation for these, please.

**Comment by giladsharir** [comment]
GZSL is the accuracy of the model on the full set of unseen + seen labels. 
To obtain these mAP values, you will have to replace ```test_wordvecs``` with a concatenation of ```test_wordvecs``` and ```train_wordvecs``` in the train_zsl code.
F1 score is a standard calculation.

**Comment by aliman80** [comment]
Thank you so very much
________________________________
