### ISSUE TITLE
Train on Stanford Cars-196

### ISSUE THREAD

**Issue by victoic** [Alibaba-MIIL/ML_Decoder#8]
How can I reproduce the training on the Stanford Cars dataset?
The current code seems to expect COCO annotation files, but that's not what's available for Cars. Do I need to adapt the Data Loaders for the COCO dataset or can you make the train script available?

Thanks in advance.

**Comment by mrT23** [comment]
I will not share a training code for Stanford-cars, sorry

a model is provided to validate the actual result
https://github.com/Alibaba-MIIL/ML_Decoder/blob/main/MODEL_ZOO.md

**Comment by sorrowyn** [comment]
> I will not share a training code for Stanford-cars, sorry
> 
> a model is provided to validate the actual result https://github.com/Alibaba-MIIL/ML_Decoder/blob/main/MODEL_ZOO.md

You can share a training config file  or the training details for Stanford-cars.
best wishes!
