### ISSUE TITLE
error happened while trainning with multi-label(self-data)：

### ISSUE THREAD

**Issue by fourmi1995** [Alibaba-MIIL/ML_Decoder#9]
cmd: CUDA_VISIBLE_DEVICES=6 python train.py --data=/DATA2/disk1/fourmi/images/data/images/data/ --model-name=tresnet_l --image-size=448

  
File "/home/fourmi/.conda/envs/ASL/lib/python3.6/site-packages/inplace_abn/functions.py", line 85, in forward
    count_ = count.to(dtype=var.dtype)
RuntimeError: CUDA error: invalid device function

it caused in here  ：ML_Decoder/src_files/models/tresnet/tresnet.py  line:210
 def forward(self, x):        
        x = self.body(x)    #the shape of x is right(b,48,112,112)
        print(x)

**Comment by mrT23** [comment]
triple-check that your GPU works well.
are you able to train with ResNet50 ?

also try to reinstall inplace-abn
